# Generated by Django 5.0.6 on 2024-05-30 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_sings',
            },
        ),
        migrations.CreateModel(
            name='SingsRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('dock', models.FileField(blank=True, null=True, upload_to='dock/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.categorysings')),
            ],
            options={
                'db_table': 'sings_road',
            },
        ),
    ]
